CREATE USER admin IDENTIFIED BY admin123;
GRANT ALL PRIVILEGES TO admin;

-- Mudar para o PDB (necessário no Oracle XE 21c)
ALTER SESSION SET CONTAINER = XEPDB1;

-- Criar usuário (ignorar erro se já existir)
DECLARE
    v_count NUMBER;
BEGIN
    SELECT COUNT(*) INTO v_count FROM dba_users WHERE username = 'ADMIN';

    IF v_count = 0 THEN
        EXECUTE IMMEDIATE 'CREATE USER admin IDENTIFIED BY admin123';
        EXECUTE IMMEDIATE 'GRANT CONNECT, RESOURCE, CREATE SESSION, CREATE TABLE, UNLIMITED TABLESPACE TO admin';
    END IF;
END;
/

-- Definir o usuário para criação das tabelas
ALTER SESSION SET CURRENT_SCHEMA = admin;

CREATE TABLE users (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR2(50) NOT NULL UNIQUE,
    password VARCHAR2(255) NOT NULL,
    name VARCHAR2(100),
    role VARCHAR2(20) DEFAULT 'ROLE_USER',
    active NUMBER(1) DEFAULT 1
);

CREATE TABLE products (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR2(100) NOT NULL,
    description VARCHAR2(4000),
    quantity NUMBER DEFAULT 0,
    price NUMBER(10,2) DEFAULT 0,
    active NUMBER(1) DEFAULT 1
);
CREATE TABLE orders (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id NUMBER NOT NULL,
    product_id NUMBER NOT NULL,
    quantity NUMBER DEFAULT 1,
    price NUMBER(10,2) NOT NULL,
    purchase_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_order_user FOREIGN KEY(user_id) REFERENCES users(id),
    CONSTRAINT fk_order_product FOREIGN KEY(product_id) REFERENCES products(id)
);

CREATE OR REPLACE PROCEDURE register_order(
    p_user_id IN NUMBER,
    p_product_id IN NUMBER,
    p_quantity IN NUMBER
)
AS
    v_product_quantity NUMBER;
BEGIN
    -- verifica se o produto existe e está ativo
    SELECT quantity INTO v_product_quantity
    FROM products
    WHERE id = p_product_id AND active = 1;

    IF v_product_quantity < p_quantity THEN
        RAISE_APPLICATION_ERROR(-20001, 'Quantidade insuficiente em estoque');
    END IF;

    -- insere o pedido
    INSERT INTO orders(user_id, product_id, quantity, price)
    SELECT p_user_id, id, p_quantity, price
    FROM products
    WHERE id = p_product_id;

    -- atualiza o estoque
    UPDATE products
    SET quantity = quantity - p_quantity
    WHERE id = p_product_id;
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        RAISE_APPLICATION_ERROR(-20002, 'Produto não encontrado ou inativo');
END;

CREATE OR REPLACE VIEW user_order_history AS
SELECT 
    u.id AS user_id,
    u.username,
    o.id AS order_id,
    o.product_id,
    p.name AS product_name,   -- <- aqui adiciona o nome do produto
    o.quantity,
    o.price,
    o.purchase_date
FROM users u
JOIN orders o ON u.id = o.user_id
JOIN products p ON o.product_id = p.id;


